apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ toYaml .Values.api.labels | nindent 6 }}
  template:
    metadata:
      labels: {{ toYaml .Values.api.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.api.port }}