apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  selector: {{ toYaml .Values.api.labels | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.api.port }}